#!/usr/bin/env python3
"""CLI for mcp_server MCP server.

Generated by: fastmcp generate-cli src/onelens/mcp_server.py
"""

import json
import sys
from typing import Annotated

import cyclopts
import mcp.types
from rich.console import Console

from fastmcp import Client

# In-process transport — no subprocess, no PATH dependency on `fastmcp` binary.
from onelens.mcp_server import mcp as _server
CLIENT_SPEC = _server

app = cyclopts.App(name="mcp_server", help="CLI for mcp_server MCP server")
call_tool_app = cyclopts.App(name="call-tool", help="Call a tool on the server")
app.command(call_tool_app)

console = Console()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _print_tool_result(result):
    if result.is_error:
        for block in result.content:
            if isinstance(block, mcp.types.TextContent):
                console.print(f"[bold red]Error:[/bold red] {block.text}")
            else:
                console.print(f"[bold red]Error:[/bold red] {block}")
        sys.exit(1)

    if result.structured_content is not None:
        console.print_json(json.dumps(result.structured_content))
        return

    for block in result.content:
        if isinstance(block, mcp.types.TextContent):
            console.print(block.text)
        elif isinstance(block, mcp.types.ImageContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Image: {block.mimeType}, ~{size} bytes][/dim]")
        elif isinstance(block, mcp.types.AudioContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Audio: {block.mimeType}, ~{size} bytes][/dim]")


async def _call_tool(tool_name: str, arguments: dict) -> None:
    # Filter out None values and empty lists (defaults for optional array params)
    filtered = {
        k: v
        for k, v in arguments.items()
        if v is not None and (not isinstance(v, list) or len(v) > 0)
    }
    async with Client(CLIENT_SPEC) as client:
        result = await client.call_tool(tool_name, filtered, raise_on_error=False)
        _print_tool_result(result)
        if result.is_error:
            sys.exit(1)


# ---------------------------------------------------------------------------
# List / read commands
# ---------------------------------------------------------------------------


@app.command
async def list_tools() -> None:
    """List available tools."""
    async with Client(CLIENT_SPEC) as client:
        tools = await client.list_tools()
        if not tools:
            console.print("[dim]No tools found.[/dim]")
            return
        for tool in tools:
            sig_parts = []
            props = tool.inputSchema.get("properties", {})
            required = set(tool.inputSchema.get("required", []))
            for pname, pschema in props.items():
                ptype = pschema.get("type", "string")
                if pname in required:
                    sig_parts.append(f"{pname}: {ptype}")
                else:
                    sig_parts.append(f"{pname}: {ptype} = ...")
            sig = f"{tool.name}({', '.join(sig_parts)})"
            console.print(f"  [cyan]{sig}[/cyan]")
            if tool.description:
                console.print(f"    {tool.description}")
            console.print()


@app.command
async def list_resources() -> None:
    """List available resources."""
    async with Client(CLIENT_SPEC) as client:
        resources = await client.list_resources()
        if not resources:
            console.print("[dim]No resources found.[/dim]")
            return
        for r in resources:
            console.print(f"  [cyan]{r.uri}[/cyan]")
            desc_parts = [r.name or "", r.description or ""]
            desc = " — ".join(p for p in desc_parts if p)
            if desc:
                console.print(f"    {desc}")
        console.print()


@app.command
async def read_resource(uri: Annotated[str, cyclopts.Parameter(help="Resource URI")]) -> None:
    """Read a resource by URI."""
    async with Client(CLIENT_SPEC) as client:
        contents = await client.read_resource(uri)
        for block in contents:
            if isinstance(block, mcp.types.TextResourceContents):
                console.print(block.text)
            elif isinstance(block, mcp.types.BlobResourceContents):
                size = len(block.blob) * 3 // 4
                console.print(f"[dim][Blob: {block.mimeType}, ~{size} bytes][/dim]")


@app.command
async def list_prompts() -> None:
    """List available prompts."""
    async with Client(CLIENT_SPEC) as client:
        prompts = await client.list_prompts()
        if not prompts:
            console.print("[dim]No prompts found.[/dim]")
            return
        for p in prompts:
            args_str = ""
            if p.arguments:
                parts = [a.name for a in p.arguments]
                args_str = f"({', '.join(parts)})"
            console.print(f"  [cyan]{p.name}{args_str}[/cyan]")
            if p.description:
                console.print(f"    {p.description}")
        console.print()


@app.command
async def get_prompt(
    name: Annotated[str, cyclopts.Parameter(help="Prompt name")],
    *arguments: str,
) -> None:
    """Get a prompt by name. Pass arguments as key=value pairs."""
    parsed: dict[str, str] = {}
    for arg in arguments:
        if "=" not in arg:
            console.print(f"[bold red]Error:[/bold red] Invalid argument {arg!r} — expected key=value")
            sys.exit(1)
        key, value = arg.split("=", 1)
        parsed[key] = value

    async with Client(CLIENT_SPEC) as client:
        result = await client.get_prompt(name, parsed or None)
        for msg in result.messages:
            console.print(f"[bold]{msg.role}:[/bold]")
            if isinstance(msg.content, mcp.types.TextContent):
                console.print(f"  {msg.content.text}")
            elif isinstance(msg.content, mcp.types.ImageContent):
                size = len(msg.content.data) * 3 // 4
                console.print(f"  [dim][Image: {msg.content.mimeType}, ~{size} bytes][/dim]")
            else:
                console.print(f"  {msg.content}")
            console.print()


# ---------------------------------------------------------------------------
# Tool commands (generated from server schema)
# ---------------------------------------------------------------------------

@call_tool_app.command(name='onelens_status')
async def onelens_status(
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordblite',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
) -> None:
    '''Session wake-up. First tool to call in every session.

Returns capabilities + node counts so the skill\'s decision tree knows
which subsequent tools to invoke (semantic retrieve vs FTS search,
SQL-surface queries vs code-only, …). Works on any graph — code
graphs, Vue3 graphs, and the palace memory graph alike.'''
    await _call_tool('onelens_status', {'graph': graph, 'backend': backend, 'db_path': db_path})


@call_tool_app.command(name='onelens_query')
async def onelens_query(
    *,
    cypher: Annotated[str, cyclopts.Parameter(help="")],
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordblite',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
    limit: Annotated[int, cyclopts.Parameter(help="")] = 100,
) -> None:
    '''Run raw Cypher against any graph. Returns up to `limit` rows.

Use this for impact analysis, trace, entry-point enumeration, schema
introspection — the skill docs have ready-made patterns for each of
those. Works on code graphs and the palace memory graph uniformly.'''
    await _call_tool('onelens_query', {'cypher': cypher, 'graph': graph, 'backend': backend, 'db_path': db_path, 'limit': limit})


@call_tool_app.command(name='onelens_search')
async def onelens_search(
    *,
    term: Annotated[str, cyclopts.Parameter(help="")],
    node_type: Annotated[str, cyclopts.Parameter(help="")] = '',
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordblite',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
    n_results: Annotated[int, cyclopts.Parameter(help="")] = 50,
) -> None:
    '''Name-based search across graph nodes (FTS, supports `User*`, `%auth%`).

`node_type`: one of "class", "method", "endpoint", "drawer", or "" for any.
For conceptual / natural-language questions, use `onelens_retrieve`
instead — that one reads actual code content.'''
    await _call_tool('onelens_search', {'term': term, 'node_type': node_type, 'graph': graph, 'backend': backend, 'db_path': db_path, 'n_results': n_results})


@call_tool_app.command(name='onelens_retrieve')
async def onelens_retrieve(
    *,
    query: Annotated[str, cyclopts.Parameter(help="")],
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    n_results: Annotated[int, cyclopts.Parameter(help="")] = 10,
    fanout: Annotated[int, cyclopts.Parameter(help="")] = 50,
    include_snippets: Annotated[bool, cyclopts.Parameter(help="")] = True,
    include_neighbors: Annotated[bool, cyclopts.Parameter(help="")] = False,
    rerank: Annotated[bool, cyclopts.Parameter(help="")] = True,
    rerank_pool: Annotated[int, cyclopts.Parameter(help="")] = 100,
    project_root: Annotated[str, cyclopts.Parameter(help="")] = '',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordblite',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
) -> None:
    '''Hybrid FTS + semantic retrieval with source code snippets.

Gated by `onelens_status.capabilities.has_semantic` — if false, fall back
to `onelens_search`. Returns top-K ranked hits with actual source code,
not just FQNs, so an LLM can read the methods directly.'''
    await _call_tool('onelens_retrieve', {'query': query, 'graph': graph, 'n_results': n_results, 'fanout': fanout, 'include_snippets': include_snippets, 'include_neighbors': include_neighbors, 'rerank': rerank, 'rerank_pool': rerank_pool, 'project_root': project_root, 'backend': backend, 'db_path': db_path})


@call_tool_app.command(name='onelens_import')
async def onelens_import(
    *,
    export_path: Annotated[str, cyclopts.Parameter(help="")],
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordblite',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
    clear: Annotated[bool, cyclopts.Parameter(help="")] = False,
    context: Annotated[bool, cyclopts.Parameter(help="")] = False,
) -> None:
    '''Import an export JSON (auto-detects full vs delta).

`context=True` also runs the ChromaDB semantic mining pass so
`onelens_retrieve` works afterwards.'''
    await _call_tool('onelens_import', {'export_path': export_path, 'graph': graph, 'backend': backend, 'db_path': db_path, 'clear': clear, 'context': context})


@call_tool_app.command(name='onelens_delta_import')
async def onelens_delta_import(
    *,
    delta_path: Annotated[str, cyclopts.Parameter(help="")],
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordblite',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
    context: Annotated[bool, cyclopts.Parameter(help="")] = False,
) -> None:
    '''Apply a delta export explicitly (bypasses the auto-detect in onelens_import).'''
    await _call_tool('onelens_delta_import', {'delta_path': delta_path, 'graph': graph, 'backend': backend, 'db_path': db_path, 'context': context})


@call_tool_app.command(name='onelens_add_drawer')
async def onelens_add_drawer(
    *,
    wing: Annotated[str, cyclopts.Parameter(help="")],
    room: Annotated[str, cyclopts.Parameter(help="")],
    content: Annotated[str, cyclopts.Parameter(help="")],
    source_file: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    added_by: Annotated[str, cyclopts.Parameter(help="")] = 'mcp',
    hall: Annotated[str, cyclopts.Parameter(help="")] = 'hall_fact',
    kind: Annotated[str, cyclopts.Parameter(help="")] = 'note',
    importance: Annotated[float, cyclopts.Parameter(help="")] = 1.0,
    fqn: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    force: Annotated[bool, cyclopts.Parameter(help="")] = False,
) -> None:
    '''Store content in a wing/room drawer. Runs embedding + dedups unless force=True.'''
    # Parse JSON parameters
    source_file_parsed = json.loads(source_file) if isinstance(source_file, str) else source_file
    fqn_parsed = json.loads(fqn) if isinstance(fqn, str) else fqn

    await _call_tool('onelens_add_drawer', {'wing': wing, 'room': room, 'content': content, 'source_file': source_file_parsed, 'added_by': added_by, 'hall': hall, 'kind': kind, 'importance': importance, 'fqn': fqn_parsed, 'force': force})


@call_tool_app.command(name='onelens_delete_drawer')
async def onelens_delete_drawer(
    *,
    drawer_id: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Delete one drawer by id.'''
    await _call_tool('onelens_delete_drawer', {'drawer_id': drawer_id})


@call_tool_app.command(name='onelens_check_duplicate')
async def onelens_check_duplicate(
    *,
    content: Annotated[str, cyclopts.Parameter(help="")],
    threshold: Annotated[float, cyclopts.Parameter(help="")] = 0.9,
    wing: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
) -> None:
    '''Semantic dedup check before `onelens_add_drawer`. Returns hits ≥ threshold.'''
    # Parse JSON parameters
    wing_parsed = json.loads(wing) if isinstance(wing, str) else wing

    await _call_tool('onelens_check_duplicate', {'content': content, 'threshold': threshold, 'wing': wing_parsed})


@call_tool_app.command(name='onelens_kg_add')
async def onelens_kg_add(
    *,
    subject: Annotated[str, cyclopts.Parameter(help="")],
    predicate: Annotated[str, cyclopts.Parameter(help="")],
    object: Annotated[str, cyclopts.Parameter(help="")],
    valid_from: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    confidence: Annotated[float, cyclopts.Parameter(help="")] = 1.0,
    source_closet: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    ended: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    wing: Annotated[str, cyclopts.Parameter(help="")] = 'global',
) -> None:
    '''Add a temporal fact triple. Dedupes by hash(s|p|o|valid_from).'''
    # Parse JSON parameters
    valid_from_parsed = json.loads(valid_from) if isinstance(valid_from, str) else valid_from
    source_closet_parsed = json.loads(source_closet) if isinstance(source_closet, str) else source_closet
    ended_parsed = json.loads(ended) if isinstance(ended, str) else ended

    await _call_tool('onelens_kg_add', {'subject': subject, 'predicate': predicate, 'object': object, 'valid_from': valid_from_parsed, 'confidence': confidence, 'source_closet': source_closet_parsed, 'ended': ended_parsed, 'wing': wing})


@call_tool_app.command(name='onelens_kg_invalidate')
async def onelens_kg_invalidate(
    *,
    fact_id: Annotated[str, cyclopts.Parameter(help="")],
    ended_at: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    reason: Annotated[str, cyclopts.Parameter(help="")] = '',
) -> None:
    '''Close an existing fact by id (temporal retraction; history preserved).'''
    # Parse JSON parameters
    ended_at_parsed = json.loads(ended_at) if isinstance(ended_at, str) else ended_at

    await _call_tool('onelens_kg_invalidate', {'fact_id': fact_id, 'ended_at': ended_at_parsed, 'reason': reason})


@call_tool_app.command(name='onelens_kg_timeline')
async def onelens_kg_timeline(
    *,
    entity: Annotated[str, cyclopts.Parameter(help="")],
    predicate: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    since: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    until: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
) -> None:
    '''Time-bucketed view of facts touching an entity — see how knowledge evolved.'''
    # Parse JSON parameters
    predicate_parsed = json.loads(predicate) if isinstance(predicate, str) else predicate
    since_parsed = json.loads(since) if isinstance(since, str) else since
    until_parsed = json.loads(until) if isinstance(until, str) else until

    await _call_tool('onelens_kg_timeline', {'entity': entity, 'predicate': predicate_parsed, 'since': since_parsed, 'until': until_parsed})


@call_tool_app.command(name='onelens_find_tunnels')
async def onelens_find_tunnels(
    *,
    wing_a: Annotated[str, cyclopts.Parameter(help="")],
    wing_b: Annotated[str, cyclopts.Parameter(help="")],
    threshold: Annotated[float, cyclopts.Parameter(help="")] = 0.7,
    n_results: Annotated[int, cyclopts.Parameter(help="")] = 20,
) -> None:
    '''Cross-wing semantic similarity — concepts shared across repos / subsystems.'''
    await _call_tool('onelens_find_tunnels', {'wing_a': wing_a, 'wing_b': wing_b, 'threshold': threshold, 'n_results': n_results})


@call_tool_app.command(name='onelens_diary_write')
async def onelens_diary_write(
    *,
    wing: Annotated[str, cyclopts.Parameter(help="")],
    content: Annotated[str, cyclopts.Parameter(help="")],
    author: Annotated[str, cyclopts.Parameter(help="")] = 'mcp',
    date: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
) -> None:
    '''Append a diary entry for `wing`. WAL-backed — crash-safe.'''
    # Parse JSON parameters
    date_parsed = json.loads(date) if isinstance(date, str) else date

    await _call_tool('onelens_diary_write', {'wing': wing, 'content': content, 'author': author, 'date': date_parsed})


@call_tool_app.command(name='onelens_diary_read')
async def onelens_diary_read(
    *,
    wing: Annotated[str, cyclopts.Parameter(help="")],
    since: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    until: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="")] = 50,
) -> None:
    '''Read diary entries for a wing, optionally time-ranged.'''
    # Parse JSON parameters
    since_parsed = json.loads(since) if isinstance(since, str) else since
    until_parsed = json.loads(until) if isinstance(until, str) else until

    await _call_tool('onelens_diary_read', {'wing': wing, 'since': since_parsed, 'until': until_parsed, 'limit': limit})


@call_tool_app.command(name='onelens_snapshot_publish')
async def onelens_snapshot_publish(
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")],
    tag: Annotated[str, cyclopts.Parameter(help="")],
    repo: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    include_embeddings: Annotated[bool, cyclopts.Parameter(help="")] = False,
    sign: Annotated[bool, cyclopts.Parameter(help="")] = True,
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'local',
) -> None:
    '''Bundle `<graph>` as `<graph>@<tag>` snapshot.

Writes an immutable tarball with bundle-internal `manifest.json`,
SHA256 checksum, and (when cosign is on PATH) a Sigstore signature.
`backend=\'github\'` uploads to GitHub Release `<tag>` on `<repo>` and
maintains a `snapshots.json` index on the pinned `onelens-index` tag.'''
    # Parse JSON parameters
    repo_parsed = json.loads(repo) if isinstance(repo, str) else repo

    await _call_tool('onelens_snapshot_publish', {'graph': graph, 'tag': tag, 'repo': repo_parsed, 'include_embeddings': include_embeddings, 'sign': sign, 'backend': backend})


@call_tool_app.command(name='onelens_snapshots_list')
async def onelens_snapshots_list(
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")],
    repo: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''List release snapshots available for `<graph>` in GitHub `<repo>`.

Reads the `snapshots.json` asset on the pinned `onelens-index` tag —
one HTTPS GET, no pagination. Returns an empty list when the repo has
never published a snapshot.'''
    await _call_tool('onelens_snapshots_list', {'graph': graph, 'repo': repo})


@call_tool_app.command(name='onelens_snapshots_pull')
async def onelens_snapshots_pull(
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")],
    tag: Annotated[str, cyclopts.Parameter(help="")],
    repo: Annotated[str, cyclopts.Parameter(help="")],
    verify: Annotated[bool, cyclopts.Parameter(help="")] = True,
) -> None:
    '''Download, verify, and install a release snapshot as `<graph>@<tag>`.

Authoritative SHA256 comes from the `snapshots.json` index, falling
back to the `.sha256` sidecar. Optionally cosign-verifies when the
`.sig` asset is present. Restored graph appears in subsequent
`onelens_status` calls under `--graph <graph>@<tag>`.'''
    await _call_tool('onelens_snapshots_pull', {'graph': graph, 'tag': tag, 'repo': repo, 'verify': verify})


@call_tool_app.command(name='onelens_snapshot_promote')
async def onelens_snapshot_promote(
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")],
    tag: Annotated[str, cyclopts.Parameter(help="")],
    commit_sha: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
) -> None:
    '''Seed the live graph from an installed `<graph>@<tag>` snapshot.

Copies the snapshot rdb + context dir into the live-graph slot,
renames the internal FalkorDB Lite graph key back to `<graph>`, and
writes `~/.onelens/graphs/<graph>/.onelens-baseline` so the next
delta sync uses the snapshot\'s commit SHA as the diff base
(avoiding a full reindex when onboarding from a release snapshot).

Marker is one-shot — DeltaTracker consumes and deletes it on the
next sync. Prerequisite: the snapshot is installed (via
`onelens_snapshots_pull --repo local`).'''
    # Parse JSON parameters
    commit_sha_parsed = json.loads(commit_sha) if isinstance(commit_sha, str) else commit_sha

    await _call_tool('onelens_snapshot_promote', {'graph': graph, 'tag': tag, 'commit_sha': commit_sha_parsed})


if __name__ == "__main__":
    app()

main = app
