#!/usr/bin/env python3
"""CLI for mcp_server MCP server.

Generated by: fastmcp generate-cli src/onelens/mcp_server.py
"""

import json
import sys
from typing import Annotated

import cyclopts

# NOTE: fastmcp.Client + mcp.types + rich.Console + pydantic pull in ~3s of
# eager imports. Defer them to the first tool invocation so `--help`,
# `daemon status`, and anything that doesn't actually hit the server stay
# sub-second.


def _build_client_spec():
    """Lazily pick HTTP daemon (warm, ~200ms) or stdio spawn (cold, ~30s)."""
    import os as _os

    from fastmcp.client.transports import StdioTransport
    from onelens.daemon import DEFAULT_PORT as _DAEMON_PORT, status as _daemon_status

    url = _os.environ.get("ONELENS_SERVER_URL")
    if not url and _daemon_status(_DAEMON_PORT)["reachable"]:
        url = f"http://127.0.0.1:{_DAEMON_PORT}/mcp/"
    if url:
        return url
    return StdioTransport(command=sys.executable, args=["-m", "onelens.mcp_server"])


class _LazyConsole:
    """Proxy for `rich.console.Console` that defers the import until used."""

    _inner = None

    def _get(self):
        if self._inner is None:
            from rich.console import Console

            self._inner = Console()
        return self._inner

    def __getattr__(self, name):
        return getattr(self._get(), name)


def _get_console():
    return console


console = _LazyConsole()

app = cyclopts.App(name="onelens", help="OneLens - Code Knowledge Graph for Java/Spring Boot")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _print_tool_result(result):
    import mcp.types as _mcp_types

    console = _get_console()
    if result.is_error:
        for block in result.content:
            if isinstance(block, _mcp_types.TextContent):
                console.print(f"[bold red]Error:[/bold red] {block.text}")
            else:
                console.print(f"[bold red]Error:[/bold red] {block}")
        sys.exit(1)

    if result.structured_content is not None:
        console.print_json(json.dumps(result.structured_content))
        return

    for block in result.content:
        if isinstance(block, _mcp_types.TextContent):
            console.print(block.text)
        elif isinstance(block, _mcp_types.ImageContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Image: {block.mimeType}, ~{size} bytes][/dim]")
        elif isinstance(block, _mcp_types.AudioContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Audio: {block.mimeType}, ~{size} bytes][/dim]")


async def _call_tool(tool_name: str, arguments: dict) -> None:
    from fastmcp import Client

    filtered = {
        k: v
        for k, v in arguments.items()
        if v is not None and (not isinstance(v, list) or len(v) > 0)
    }
    async with Client(_build_client_spec()) as client:
        result = await client.call_tool(tool_name, filtered, raise_on_error=False)
        _print_tool_result(result)
        if result.is_error:
            sys.exit(1)


# ---------------------------------------------------------------------------
# List / read commands
# ---------------------------------------------------------------------------


@app.command
async def list_tools() -> None:
    """List available tools."""
    from fastmcp import Client as _Client
    async with _Client(_build_client_spec()) as client:
        tools = await client.list_tools()
        if not tools:
            console.print("[dim]No tools found.[/dim]")
            return
        for tool in tools:
            sig_parts = []
            props = tool.inputSchema.get("properties", {})
            required = set(tool.inputSchema.get("required", []))
            for pname, pschema in props.items():
                ptype = pschema.get("type", "string")
                if pname in required:
                    sig_parts.append(f"{pname}: {ptype}")
                else:
                    sig_parts.append(f"{pname}: {ptype} = ...")
            sig = f"{tool.name}({', '.join(sig_parts)})"
            console.print(f"  [cyan]{sig}[/cyan]")
            if tool.description:
                console.print(f"    {tool.description}")
            console.print()


@app.command
async def list_resources() -> None:
    """List available resources."""
    from fastmcp import Client as _Client
    async with _Client(_build_client_spec()) as client:
        resources = await client.list_resources()
        if not resources:
            console.print("[dim]No resources found.[/dim]")
            return
        for r in resources:
            console.print(f"  [cyan]{r.uri}[/cyan]")
            desc_parts = [r.name or "", r.description or ""]
            desc = " — ".join(p for p in desc_parts if p)
            if desc:
                console.print(f"    {desc}")
        console.print()


@app.command
async def read_resource(uri: Annotated[str, cyclopts.Parameter(help="Resource URI")]) -> None:
    """Read a resource by URI."""
    from fastmcp import Client as _Client
    async with _Client(_build_client_spec()) as client:
        contents = await client.read_resource(uri)
        for block in contents:
            if isinstance(block, mcp.types.TextResourceContents):
                console.print(block.text)
            elif isinstance(block, mcp.types.BlobResourceContents):
                size = len(block.blob) * 3 // 4
                console.print(f"[dim][Blob: {block.mimeType}, ~{size} bytes][/dim]")


@app.command
async def list_prompts() -> None:
    """List available prompts."""
    from fastmcp import Client as _Client
    async with _Client(_build_client_spec()) as client:
        prompts = await client.list_prompts()
        if not prompts:
            console.print("[dim]No prompts found.[/dim]")
            return
        for p in prompts:
            args_str = ""
            if p.arguments:
                parts = [a.name for a in p.arguments]
                args_str = f"({', '.join(parts)})"
            console.print(f"  [cyan]{p.name}{args_str}[/cyan]")
            if p.description:
                console.print(f"    {p.description}")
        console.print()


@app.command
async def get_prompt(
    name: Annotated[str, cyclopts.Parameter(help="Prompt name")],
    *arguments: str,
) -> None:
    """Get a prompt by name. Pass arguments as key=value pairs."""
    parsed: dict[str, str] = {}
    for arg in arguments:
        if "=" not in arg:
            console.print(f"[bold red]Error:[/bold red] Invalid argument {arg!r} — expected key=value")
            sys.exit(1)
        key, value = arg.split("=", 1)
        parsed[key] = value

    from fastmcp import Client as _Client
    async with _Client(_build_client_spec()) as client:
        result = await client.get_prompt(name, parsed or None)
        for msg in result.messages:
            console.print(f"[bold]{msg.role}:[/bold]")
            if isinstance(msg.content, mcp.types.TextContent):
                console.print(f"  {msg.content.text}")
            elif isinstance(msg.content, mcp.types.ImageContent):
                size = len(msg.content.data) * 3 // 4
                console.print(f"  [dim][Image: {msg.content.mimeType}, ~{size} bytes][/dim]")
            else:
                console.print(f"  {msg.content}")
            console.print()


# ---------------------------------------------------------------------------
# Tool commands (generated from server schema)
# ---------------------------------------------------------------------------

@app.command(name='import_graph')
async def import_graph(
    export_path: Annotated[str, cyclopts.Parameter(help="")],
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordb',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
    clear: Annotated[bool, cyclopts.Parameter(help="")] = False,
    context: Annotated[bool, cyclopts.Parameter(help="")] = False,
) -> None:
    '''Import an export JSON (auto-detects full vs delta) into the knowledge graph.

Set context=True to also index methods/classes into ChromaDB for semantic search.'''
    await _call_tool('import_graph', {'export_path': export_path, 'graph': graph, 'backend': backend, 'db_path': db_path, 'clear': clear, 'context': context})


@app.command(name='delta_import')
async def delta_import(
    delta_path: Annotated[str, cyclopts.Parameter(help="")],
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordb',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
) -> None:
    '''Apply a delta export to an existing graph.'''
    await _call_tool('delta_import', {'delta_path': delta_path, 'graph': graph, 'backend': backend, 'db_path': db_path})


@app.command(name='stats')
async def stats(
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordb',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
) -> None:
    '''Return node counts per label for a graph.'''
    await _call_tool('stats', {'graph': graph, 'backend': backend, 'db_path': db_path})


@app.command(name='query')
async def query(
    cypher: Annotated[str, cyclopts.Parameter(help="")],
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordb',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
    limit: Annotated[int, cyclopts.Parameter(help="")] = 100,
) -> None:
    '''Run a raw Cypher query. Returns up to `limit` rows.'''
    await _call_tool('query', {'cypher': cypher, 'graph': graph, 'backend': backend, 'db_path': db_path, 'limit': limit})


@app.command(name='search')
async def search(
    term: Annotated[str, cyclopts.Parameter(help="")],
    *,
    node_type: Annotated[str, cyclopts.Parameter(help="")] = '',
    semantic: Annotated[bool, cyclopts.Parameter(help="")] = False,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordb',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
    n_results: Annotated[int, cyclopts.Parameter(help="")] = 50,
) -> None:
    '''Search code by name (FTS, supports User*, %auth%1) or by meaning (semantic=True).

node_type: one of "class", "method", "endpoint", or "" for any.
Semantic requires the graph to have been imported with context=True (ChromaDB).'''
    await _call_tool('search', {'term': term, 'node_type': node_type, 'semantic': semantic, 'graph': graph, 'backend': backend, 'db_path': db_path, 'n_results': n_results})


@app.command(name='trace')
async def trace(
    target: Annotated[str, cyclopts.Parameter(help="")],
    *,
    entry_type: Annotated[str, cyclopts.Parameter(help="")] = 'method',
    depth: Annotated[int, cyclopts.Parameter(help="")] = 5,
    http_method: Annotated[str, cyclopts.Parameter(help="")] = '',
    include_external: Annotated[bool, cyclopts.Parameter(help="")] = False,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordb',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
) -> None:
    '''Trace execution flow forward from an entry point.

target: method FQN or endpoint path. depth: 1-5.'''
    await _call_tool('trace', {'target': target, 'entry_type': entry_type, 'depth': depth, 'http_method': http_method, 'include_external': include_external, 'graph': graph, 'backend': backend, 'db_path': db_path})


@app.command(name='entry_points')
async def entry_points(
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordb',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
) -> None:
    '''List all entry points (REST endpoints, @Scheduled methods, main()).'''
    await _call_tool('entry_points', {'graph': graph, 'backend': backend, 'db_path': db_path})


@app.command(name='impact')
async def impact(
    method_fqn: Annotated[str, cyclopts.Parameter(help="")],
    *,
    depth: Annotated[int, cyclopts.Parameter(help="")] = 5,
    polymorphic: Annotated[bool, cyclopts.Parameter(help="")] = True,
    bean_filter: Annotated[bool, cyclopts.Parameter(help="")] = True,
    precise_only: Annotated[bool, cyclopts.Parameter(help="")] = False,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordb',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
) -> None:
    '''Find REST endpoints impacted if method_fqn changes.

polymorphic: walk OVERRIDES for interface/template-method dispatch (default on).
bean_filter: narrow polymorphic hits to controllers with a field of the target\'s type.
precise_only: show only endpoints reached via direct CALLS edges.'''
    await _call_tool('impact', {'method_fqn': method_fqn, 'depth': depth, 'polymorphic': polymorphic, 'bean_filter': bean_filter, 'precise_only': precise_only, 'graph': graph, 'backend': backend, 'db_path': db_path})


@app.command(name='retrieve')
async def retrieve(
    query: Annotated[str, cyclopts.Parameter(help="")],
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    n_results: Annotated[int, cyclopts.Parameter(help="")] = 10,
    fanout: Annotated[int, cyclopts.Parameter(help="")] = 50,
    include_snippets: Annotated[bool, cyclopts.Parameter(help="")] = True,
    include_neighbors: Annotated[bool, cyclopts.Parameter(help="")] = False,
    rerank: Annotated[bool, cyclopts.Parameter(help="")] = True,
    rerank_pool: Annotated[int, cyclopts.Parameter(help="")] = 50,
    project_root: Annotated[str, cyclopts.Parameter(help="")] = '',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordb',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
) -> None:
    '''Hybrid FTS + semantic retrieval with source code snippets (Augment-parity).

Returns top-K ranked hits with actual source code ready for an LLM to read.
Requires both FalkorDB (structural) and --context (ChromaDB) indexed.
project_root can be set via ONELENS_PROJECT_ROOT env if not passed.'''
    await _call_tool('retrieve', {'query': query, 'graph': graph, 'n_results': n_results, 'fanout': fanout, 'include_snippets': include_snippets, 'include_neighbors': include_neighbors, 'rerank': rerank, 'rerank_pool': rerank_pool, 'project_root': project_root, 'backend': backend, 'db_path': db_path})


@app.command(name='context_import')
async def context_import(
    export_path: Annotated[str, cyclopts.Parameter(help="")],
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
) -> None:
    '''Index a JSON export into ChromaDB for semantic search (standalone, no FalkorDB).'''
    await _call_tool('context_import', {'export_path': export_path, 'graph': graph})


@app.command(name='context_search')
async def context_search(
    query: Annotated[str, cyclopts.Parameter(help="")],
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    entity_type: Annotated[str, cyclopts.Parameter(help="")] = '',
    room: Annotated[str, cyclopts.Parameter(help="")] = '',
    n_results: Annotated[int, cyclopts.Parameter(help="")] = 10,
) -> None:
    '''Pure semantic search over ChromaDB (no FalkorDB).

entity_type: one of "method", "class", "endpoint", or "" for any.
room: Java package name filter, or "" for none.'''
    await _call_tool('context_search', {'query': query, 'graph': graph, 'entity_type': entity_type, 'room': room, 'n_results': n_results})


@app.command(name='context_wakeup')
async def context_wakeup(
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    backend: Annotated[str, cyclopts.Parameter(help="")] = 'falkordb',
    db_path: Annotated[str, cyclopts.Parameter(help="")] = '~/.onelens/graphs',
) -> None:
    '''Generate L0+L1 context (~900 tokens) for AI system prompt injection.'''
    await _call_tool('context_wakeup', {'graph': graph, 'backend': backend, 'db_path': db_path})


@app.command(name='context_recall')
async def context_recall(
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
    room: Annotated[str, cyclopts.Parameter(help="")] = '',
    entity_type: Annotated[str, cyclopts.Parameter(help="")] = '',
    n_results: Annotated[int, cyclopts.Parameter(help="")] = 10,
) -> None:
    '''L2 filtered retrieval by package (room) or entity type.

entity_type: "method", "class", "endpoint", or "" for any.'''
    await _call_tool('context_recall', {'graph': graph, 'room': room, 'entity_type': entity_type, 'n_results': n_results})


@app.command(name='context_stats')
async def context_stats(
    *,
    graph: Annotated[str, cyclopts.Parameter(help="")] = 'onelens',
) -> None:
    '''Show context graph (ChromaDB) statistics.'''
    await _call_tool('context_stats', {'graph': graph})


# ---------------------------------------------------------------------------
# Daemon lifecycle (not MCP tools — manage the long-running warm server)
# ---------------------------------------------------------------------------

daemon_app = cyclopts.App(name="daemon", help="Manage the long-running warm MCP HTTP server")
app.command(daemon_app)


@daemon_app.command(name="start")
def daemon_start(
    *,
    port: Annotated[int, cyclopts.Parameter(help="Bind port")] = 8765,
) -> None:
    """Start the MCP HTTP daemon with eager Qwen3 + mxbai-rerank warmup (~30s).

    Subsequent `onelens` calls auto-detect it and use warm path (~200ms).
    """
    from onelens import daemon as _d

    console.print_json(json.dumps(_d.start(port)))


@daemon_app.command(name="stop")
def daemon_stop(
    *,
    port: Annotated[int, cyclopts.Parameter(help="Daemon port")] = 8765,
) -> None:
    """Stop the MCP HTTP daemon."""
    from onelens import daemon as _d

    console.print_json(json.dumps(_d.stop(port)))


@daemon_app.command(name="status")
def daemon_status(
    *,
    port: Annotated[int, cyclopts.Parameter(help="Daemon port")] = 8765,
) -> None:
    """Show daemon status (pid, reachable, log path)."""
    from onelens import daemon as _d

    console.print_json(json.dumps(_d.status(port)))


def main() -> None:
    """Entry point for the `onelens` console script."""
    app()


if __name__ == "__main__":
    main()
